name: Crawl hydrodata(hbsl) schedulely

on:
  push:
    branches:
      - main:
    
jobs:
  crawl-hbsl:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.TEST_TOKEN }}" \
          --data '{"event_type": "datong"}' \
          https://api.github.com/repos/longavailable/test1/dispatches
